---
- name: Restart Pods
  hosts: all
  vars:
    name_space: "-n default"

  tasks:

    - name: This will now delete pods by name
      shell: for POD in `/usr/local/bin/kubectl get pod --namespace default -l name=fluentd-rabbit | tail -n +2 | awk '{print $1}'`; do echo RELOAD ${POD}; /usr/local/bin/kubectl delete pod ${POD} --namespace default ; done
      register: kubectl

    - debug: msg="{{ kubectl.stdout }}"
