---
- name: Adding Kops and Kubectl
  hosts: all
  roles:
    - andrewrothstein.kubectl

  tasks:
#     - name: Add epel-release repo
#       yum:
#         name: epel-release
#         state: present
#     - name: List ansible packages and register result to print with debug later.
#       yum:
#         list: ansible
#       register: result
      
#     - name: Add K8 Repo
#       yum_repository:
#         name: kubernetes
#         description: Some YUM repo
#         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
#         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#         gpgcheck: yes
#         repo_gpgcheck: no
#         state: present
        
#     - name: Install Kubectl
#       yum:
#         name: kubectl
#         enablerepo: kubernetes
#         state: present

    - name: Installing Kops Now
      get_url:
        url: https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64
        dest: /usr/local/bin/kops
        mode: a+x

    - name: list namespaces
      shell: kubectl get pods
