---
- name: date
  hosts: all

  tasks:

  - name: date
#    shell: kubectl run test --rm --requests="cpu=500m,memory=512Mi" --limits="cpu=500m,memory=512Mi" -n sandbox --restart=Never -it --image=alpine date
#    shell: kubectl get pods --all-namespaces
    shell:  kubectl get pods --all-namespaces
---
- name: Hello World!
  hosts: all

  tasks:

  - name: Hello World!
    shell: echo "Hi! Tower is working!"
