---
- name: Adding Kops and Kubectl
  hosts: all
  vars:
    name_space: "-n default"
  roles:
    - andrewrothstein.kubectl

  tasks:


    - name: Installing Kops Now
      get_url:
        url: https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64
        dest: /usr/local/bin/kops
        mode: a+x

    - name: list namespaces
      shell: /usr/local/bin/kubectl get pods {{ name_space }}
      register: kubectl

    - debug: msg="{{ kubectl.stdout }}"

