---
- name: Shelling
  hosts: all

  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install Kubectl
      yum:
        name: kubectl
        state: present
